### ISSUE TITLE
Adicionar Favicon

### ISSUE THREAD

**Issue by ssscassio** [devfsa/devfsa.github.io#10]
Já existe algum criado ou alguma ideia? 

@salatielq

**Comment by salatielsql** [comment]
@ssscassio, Acredito que o D do DEVFSA vai ficar legal: 

![favicon-devfsa](https://user-images.githubusercontent.com/6747627/49036013-b1cd9580-f19d-11e8-82c3-1fd9b8f5279b.png)

**Comment by di3goleite** [comment]
Thank you guys! 💪
