### ISSUE TITLE
Integração com DevFSA Talks

### ISSUE THREAD

**Issue by ssscassio** [devfsa/devfsa.github.io#15]
Seria válido a inclusão dos vídeos do DevFSA talks no site?
Se sim, como seria? 
Adição de um link no cabeçalho para direcionar para o [youtube](https://www.youtube.com/channel/UC1E4DKVVg1Fnpjidi4XQfaw) ou adição de uma nova seção no site para assistir as talks direto por ele?

_[Off Topic] Da para mudar a url do canal de (https://www.youtube.com/channel/UC1E4DKVVg1Fnpjidi4XQfaw) para (https://www.youtube.com/channel/devfsa)?_

**Comment by di3goleite** [comment]
Oi @ssscassio . Ainda não tive tempo para responder essas issues pois tive uma semana muito corrida. Estou correndo atrás aos poucos e até este fim de semana contribuo com as discussões. ;)

**Comment by rafaelverger** [comment]
I don't know this can help, but: https://stackoverflow.com/a/47800219/1197796

**Comment by rafaelverger** [comment]
I think a page with all videos could be a good thing... also we could check in youtube if there is any live stream running when users access home page and show the live to them.

**Comment by di3goleite** [comment]
@ssscassio ainda não podemos criar um nome personalizado para o nosso canal do youtube. Segue o link para referência: https://support.google.com/youtube/answer/2657968?hl=pt-BR
![image](https://user-images.githubusercontent.com/5348158/50061071-b7097900-017a-11e9-9329-688b83b74ccb.png)

**Comment by di3goleite** [comment]
Acredito que seja melhor fechar essa issue e abrir quando tivermos atingido todos os requisitos listados acima. Brigadão pela força e desculpa a demora em responder vocês, pessoal.  💪
